### ISSUE TITLE
I first install this package  get the error below.

### ISSUE THREAD

**Issue by lymenglei** [travs/markdown-pdf#102]
OS: ubuntu 14.04 in VMware. 
if this error is not important , just ignore this:)
below is the message.

```
> phantomjs@1.9.19 install /tmp/apm-install-dir-116217-3704-1su0leq/node_modules/markdown-pdf/node_modules/html-pdf/node_modules/phantomjs
> node install.js

PhantomJS not found on PATH
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Receiving...


npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated npmconf@2.1.1: this package has been reintegrated into npm and is now out of date with respect to npm
Error making request.
Error: connect ECONNREFUSED
    at errnoException (net.js:905:11)
    at Object.afterConnect [as oncomplete] (net.js:896:19)

Please report this full log at https://github.com/Medium/phantomjs
npm ERR! Linux 3.13.0-79-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/menglei/.atom/.apm/.apmrc" "--userconfig" "/home/menglei/.atom/.apmrc" "install" "/tmp/d-116217-3704-1dvis15/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.19 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.19 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-116217-3704-1su0leq/npm-debug.log
```

**Comment by travs** [comment]
I have had some problems with the availability of phatomJS in the past, but it was usually resolved by restarting atom and trying again.

Reopen this one if the issue persists.
