### ISSUE TITLE
Uncaught Error: Notification must be created with string message: AssertionError: html-pdf: Faile...

### ISSUE THREAD

**Issue by johnshen1990** [travs/markdown-pdf#103]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.3
**Thrown From**: [markdown-pdf](https://github.com/travs/markdown-pdf) package, v1.4.2

### Stack Trace

Uncaught Error: Notification must be created with string message: AssertionError: html-pdf: Failed to load PhantomJS module. You have to set the path to the PhantomJS binary using 'options.phantomPath'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/notification.js:25

Error: Notification must be created with string message: AssertionError: html-pdf: Failed to load PhantomJS module. You have to set the path to the PhantomJS binary using 'options.phantomPath'
    at Notification.module.exports.Notification.validate (/Applications/Atom.app/Contents/Resources/app.asar/src/notification.js:25:15)
    at new Notification (/Applications/Atom.app/Contents/Resources/app.asar/src/notification.js:20:12)
    at NotificationManager.module.exports.NotificationManager.addError (/Applications/Atom.app/Contents/Resources/app.asar/src/notification-manager.js:41:35)
    at atom-workspace.module.exports.convert (/Users/john/.atom/packages/markdown-pdf/lib/markdown-pdf.js:74:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
     -0:01.2.0 markdown-pdf:convert (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
markdown-pdf, v1.4.2
markdown-preview-plus, v2.2.2
markdown-scroll-sync, v2.1.2
markdown-table-formatter, v2.8.0
pretty-json, v0.4.1

# Dev
No dev packages
```

**Comment by travs** [comment]
This one pops up a bit.

Seems to be a problem with phantomJS availability, but not sure.

Uninstalling/reinstalling the markdown-pdf package may be a potential fix.

**Comment by ckmilse** [comment]
In china, it could be very very slow, to get https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-macosx.zip
