### ISSUE TITLE
PhantomJS failing while converting CSS file

### ISSUE THREAD

**Issue by mike10010100** [travs/markdown-pdf#124]
Here is my full stack trace from trying to convert a .md file.

`stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: Command failed: /usr/local/lib/node_modules/markdown-pdf/node_modules/phantomjs/lib/phantom/bin/phantomjs /usr/local/lib/node_modules/markdown-pdf/phantom/render.js /var/folders/qj/_d_0t5vs60j4nj08vjb8wdwm0000gq/T/tmp-34695Is450RPnvRU1.html /var/folders/qj/_d_0t5vs60j4nj08vjb8wdwm0000gq/T/tmp-34695GgkkGiL6dNjJ.pdf /Users/michaelpaulauski/git/core /usr/local/lib/node_modules/markdown-pdf/runnings.js /usr/local/lib/node_modules/markdown-pdf/css/pdf.css /usr/local/lib/node_modules/markdown-pdf/css/highlight.css A4 portrait 1cm 0 10000

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)`

npm --version: 3.10.7
node --version: 6.6.0
markdown-pdf -v: 6.0.0
OS X Sierra

Thanks for the help!

**Comment by mike10010100** [comment]
Never mind. Had to separately run `npm install -g phantomjs-prebuilt`. Now it works!
