### ISSUE TITLE
Failed to activate the markdown-pdf package

### ISSUE THREAD

**Issue by zhuhewie** [travs/markdown-pdf#149]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [markdown-pdf](https://github.com/travs/markdown-pdf) package 1.5.0

### Stack Trace

Failed to activate the markdown-pdf package

```
At Cannot find module 'html-pdf'

Error: Cannot find module 'html-pdf'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.14.3/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/markdown-pdf/lib/markdown-pdf.js:2:11)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:207:16)
    at /app.asar/src/package.js:876:25
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:240:20)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1164:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:320:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:31.7.0 markdown-pdf:convert (input.hidden-input)
     -0:54.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
markdown-pdf 1.5.0 
```

**Comment by elmagnificogi** [comment]
i have the same problem too.

**Comment by LemonGirl** [comment]
I got error like this:
![image](https://user-images.githubusercontent.com/15192450/54574868-e635bd80-49e9-11e9-945c-2e6ff0c080a9.png)

**Comment by lijkjohn2005** [comment]
Me too

**Comment by lijkjohn2005** [comment]
Cannot find module 'less'
Hide Stack Trace
Error: Cannot find module 'less'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (C:\Users\lijiongkai\AppData\Local\atom\app-1.44.0\resources\electron.asar\common\reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (C:\Users\lijiongkai\AppData\Local\atom\app-1.44.0\resources\app\static\<embedded>:11:155413)
    at Module.require (file:///C:/Users/lijiongkai/AppData/Local/atom/app-1.44.0/resources/app.asar/static/index.js:61:43)
    at require (C:\Users\lijiongkai\AppData\Local\atom\app-1.44.0\resources\app\static\<embedded>:11:146745)
    at loadDeps (file:///C:/Users/lijiongkai/.atom/packages/markdown-pdf-master/lib/markdown-pdf.js:14:10)
    at Object.activate (file:///C:/Users/lijiongkai/.atom/packages/markdown-pdf-master/lib/markdown-pdf.js:74:5)
    at Package.activateNow (C:\Users\lijiongkai\AppData\Local\atom\app-1.44.0\resources\app\static\<embedded>:11:3319936)
    at activationCommandSubscriptions.add.commandRegistry.onWillDispatch.o (C:\Users\lijiongkai\AppData\Local\atom\app-1.44.0\resources\app\static\<embedded>:14:1879)
    at Function.simpleDispatch (C:\Users\lijiongkai\AppData\Local\atom\app-1.44.0\resources\app\static\<embedded>:11:1212986)
    at Emitter.emit (C:\Users\lijiongkai\AppData\Local\atom\app-1.44.0\resources\app\static\<embedded>:11:1214427)
    at CommandRegistry.handleCommandEvent (C:\Users\lijiongkai\AppData\Local\atom\app-1.44.0\resources\app\static\<embedded>:11:348922)
    at CommandRegistry.dispatch (C:\Users\lijiongkai\AppData\Local\atom\app-1.44.0\resources\app\static\<embedded>:11:347765)
    at AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\lijiongkai\AppData\Local\atom\app-1.44.0\resources\app\static\<embedded>:1:764636)
    at EventEmitter.t (C:\Users\lijiongkai\AppData\Local\atom\app-1.44.0\resources\app\static\<embedded>:1:772559)
    at EventEmitter.emit (events.js:182:13)

**Comment by janeluyip** [comment]
my report is

Cannot find module 'less'
Hide Stack Trace
Error: Cannot find module 'less'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (C:\Users\LU\AppData\Local\atom\app-1.45.0\resources\electron.asar\common\reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (C:\Users\LU\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:155413)
    at Module.require (file:///C:/Users/LU/AppData/Local/atom/app-1.45.0/resources/app.asar/static/index.js:61:43)
    at require (C:\Users\LU\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:146745)
    at Object.<anonymous> (file:///C:/Users/LU/.atom/packages/markdown-pdf/lib/actions/convert.js:4:20)
    at Object.<anonymous> (file:///C:/Users/LU/.atom/packages/markdown-pdf/lib/actions/convert.js:114:2)
    at Module.get_Module._compile (C:\Users\LU\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:147429)
    at Object.value [as .js] (C:\Users\LU\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (file:///C:/Users/LU/AppData/Local/atom/app-1.45.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\LU\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:146745)
    at Object.<anonymous> (file:///C:/Users/LU/.atom/packages/markdown-pdf/lib/markdown-pdf.js:4:30)
    at Object.<anonymous> (file:///C:/Users/LU/.atom/packages/markdown-pdf/lib/markdown-pdf.js:29:2)
    at Module.get_Module._compile (C:\Users\LU\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:147429)
    at Object.value [as .js] (C:\Users\LU\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (file:///C:/Users/LU/AppData/Local/atom/app-1.45.0/resources/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (C:\Users\LU\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:1:721712)
    at Package.requireMainModule (C:\Users\LU\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:3338526)
    at Package.activateNow (C:\Users\LU\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:3326510)
    at activationCommandSubscriptions.add.commandRegistry.onWillDispatch.o (C:\Users\LU\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:14:1879)
    at Function.simpleDispatch (C:\Users\LU\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:1214120)
    at Emitter.emit (C:\Users\LU\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:1215561)
    at CommandRegistry.handleCommandEvent (C:\Users\LU\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:348922)

**Comment by travs** [comment]
@janeluyip See https://github.com/travs/markdown-pdf/issues/181#issuecomment-603619735
