### ISSUE TITLE
Bug in path to Atom packages in Windows 10

### ISSUE THREAD

**Issue by danielzoeller** [travs/markdown-pdf#164]
It appears that there is a bug in 2.0 as I wasn't seeing this error in the previous version

`markdown-pdf: TypeError: Cannot read property 'getFileName' of undefined
 at HTMLElement.convert (C:\Users\danzo.atom\packages\markdown-pdf\lib\markdown-pdf.js:45:34)
 at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\danzo\AppData\Local\atom\app-1.19.3\resources\app\src\command-registry.js:265:35)
 at CommandRegistry.handleCommandEvent (C:\Users\danzo\AppData\Local\atom\app-1.19.3\resources\app\src\command-registry.js:3:65)
 at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\danzo\AppData\Local\atom\app-1.19.3\resources\app\src\command-registry.js:166:25)
 at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\danzo\AppData\Local\atom\app-1.19.3\resources\app\src\atom-environment.js:1338:34)
 at EventEmitter.outerCallback (C:\Users\danzo\AppData\Local\atom\app-1.19.3\resources\app\src\application-delegate.js:334:31)
 at emitThree (events.js:116:13) at EventEmitter.emit (events.js:194:7)`

**Comment by vito0719** [comment]
I have a similar issue. Can't convert...

**Comment by travs** [comment]
@vito0719 
@danielzoeller 
Ok, will revert to the old version for now, then re-release 2.0 when I test on windows 10.

**Comment by danielzoeller** [comment]
Thanks, it's working again. Anything I can help you test on Windows 10?  It seems that workspace.getActiveTextEditor() is returning null.

**Comment by travs** [comment]
@danielzoeller 
This is bizarre. Can you do `atom --version` and tell me what you get?

I just got a hold of a windows 10  machine and `2.0.0` is working on a fresh install of Atom, so I am really confused as to why this is occurring for you.

I can get that exact error if I close the text editor pane I am using before converting; do you think it is possible you had closed a pane before issuing the `convert` command?

You can get the previous version by `apm install markdown-pdf@2.0.0` (and revert to the new one with `apm install markdown-pdf@2.0.1`).

If you can give it a try and see if there is any way to reproduce the error, or if it is just always occurring, it would be a great help :)

**Comment by danielzoeller** [comment]
I'm definitely on the latest version of Atom (1.19.4).  I didn't specifically close the text editor pane, so I don't think that was it.  But I upgraded to your latest 2.0.3 and it's working fine now.
