### ISSUE TITLE
can't find module 'less'

### ISSUE THREAD

**Issue by Holy-Shine** [travs/markdown-pdf#181]
when I choose the option 'markdown to pdf', the error occurs like this:

Failed to activate the markdown-pdf package
**Cannot find module 'less'**

    Error: Cannot find module 'less'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/opt/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/opt/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (file:///opt/atom/resources/app.asar/static/index.js:40:43)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at loadDeps (/home/holyshine/.atom/packages/travs-markdown-pdf-a4918aa/lib/markdown-pdf.js:14:10)
    at Object.activate (/home/holyshine/.atom/packages/travs-markdown-pdf-a4918aa/lib/markdown-pdf.js:50:5)
    at Package.module.exports.Package.activateNow (/opt/atom/resources/app/src/package.js:253:25)
    at /opt/atom/resources/app/src/package.js:984:31
    at Function.module.exports.Emitter.simpleDispatch (/opt/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:353:24)
    at CommandRegistry.dispatch (/opt/atom/resources/app/src/command-registry.js:266:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/opt/atom/resources/app/src/atom-environment.js:1382:34)
    at EventEmitter.outerCallback (/opt/atom/resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)`

**Comment by qiyexue777** [comment]
I just have the same issue

**Comment by Holy-Shine** [comment]
Now I use another plugin called "Markdown Preview Enhanced". I think it is useful

**Comment by Holy-Shine** [comment]
@qiyexue777 Now I use another plugin called "Markdown Preview Enhanced". I think it is useful

**Comment by jantonioavalos** [comment]
Same issue :(

**Comment by Musickiller** [comment]
@jantonioavalos @qiyexue777 @Holy-Shine try installing that module =)

`npm install -g less`

**Comment by travs** [comment]
Unable to reproduce, but this sounds like a strange one.
Anyone who can reproduce this issue, please add your system information, atom version, etc. and let's see what's causing it.

**Comment by quanticle** [comment]
I'm getting the error with Atom 1.27.2 x64 on Ubuntu 18.04. 

Stack trace: 
```
Error: Cannot find module 'less'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at loadDeps (/home/quanticle/.atom/packages/markdown-pdf/lib/markdown-pdf.js:14:10)
    at Object.activate (/home/quanticle/.atom/packages/markdown-pdf/lib/markdown-pdf.js:74:5)
    at Package.activateNow (/usr/share/atom/resources/app/src/package.js:230:33)
    at activationCommandSubscriptions.add.commandRegistry.onWillDispatch.event (/usr/share/atom/resources/app/src/package.js:865:28)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:360:24)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app/src/atom-environment.js:1347:25)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app/src/application-delegate.js:339:53)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)
```

**Comment by ChaosVan** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.3
**Thrown From**: [markdown-pdf](https://github.com/travs/markdown-pdf) package 2.3.3


### Stack Trace

Failed to activate the markdown-pdf package

```
At Cannot find module 'less'

Error: Cannot find module 'less'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/markdown-pdf-master/lib/actions/convert.js:4:20)
    at /packages/markdown-pdf-master/lib/actions/convert.js:114:2)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/markdown-pdf-master/lib/markdown-pdf.js:4:30)
    at /packages/markdown-pdf-master/lib/markdown-pdf.js:29:2)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:695134)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3233575)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3221559)
    at activationCommandSubscriptions.add.commandRegistry.onWillDispatch.o (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1879)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1214120)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1215561)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:348922)
```

### Commands

```
     -4:13.1.0 editor:select-to-end-of-line (input.hidden-input)
     -4:07.2.0 markdown-pdf:convert (input.hidden-input)
     -1:14.5.0 core:select-all (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -1:05.6.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
markdown-pdf 2.3.3 
```

**Comment by travs** [comment]
@ChaosVan Going out on a limb here, but might it be that these dependencies aren't downloading due to firewalls? Try the solutions mentioned [here](https://stackoverflow.com/questions/22764407/npm-install-goes-to-dead-in-china/27216097#27216097) and [here](https://discuss.atom.io/t/apm-cant-install-package-from-china/4828) and let me know if either of them work.

As a last resort, you could try going to the package in the atom config dir (mine is `~/.atom/packages/markdown-pdf` and run `npm i` from there.

**Comment by ClackyClacky** [comment]
It's 100% because of Firewalls, Is there anyway to get the source from somewhere and install that to get around it?

**Comment by travs** [comment]
@ClackyClacky https://github.com/less/less.js/ , but first would try to use an alternative npm repo like in one of the links I gave
