### ISSUE TITLE
Markdown-pdf: Error. Check console for more information

### ISSUE THREAD

**Issue by babyhai** [travs/markdown-pdf#192]
![image](https://user-images.githubusercontent.com/22759331/40532289-905365e0-6031-11e8-9674-bfb889a468a0.png)

安装成功后，点击Packages > Markdown PDF > Convert 提示：Markdown-pdf: Error. Check console for more information

**Comment by travs** [comment]
Please check the console and post the error message here

**Comment by c-Janey** [comment]
AssertionError: html-pdf: Failed to load PhantomJS module. You have to set the path to the PhantomJS binary using 'options.phantomPath'
    at new PDF (/Users/.../.atom/packages/markdown-pdf/node_modules/mdpdf/node_modules/html-pdf/lib/pdf.js:38:3)
    at Object.createPdf [as create] (/Users/.../.atom/packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/dependencies/node-html-pdf/index.js:10:14)
    at Promise (/Users/.../.atom/packages/markdown-pdf/node_modules/mdpdf/index.js:177:7)
    at Promise._execute (/Users/.../.atom/packages/markdown-pdf/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/Users/.../.atom/packages/markdown-pdf/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/.../.atom/packages/markdown-pdf/node_modules/bluebird/js/release/promise.js:79:10)
    at createPdf (/Users/./.atom/packages/markdown-pdf/node_modules/mdpdf/index.js:176:9)
    at readFile.then.then.then.then.md (/Users/./.atom/packages/markdown-pdf/node_modules/mdpdf/index.js:169:10)
    at tryCatcher (/Users/./.atom/packages/markdown-pdf/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/./.atom/packages/markdown-pdf/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/./.atom/packages/markdown-pdf/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/./.atom/packages/markdown-pdf/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/./.atom/packages/markdown-pdf/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/./.atom/packages/markdown-pdf/node_modules/bluebird/js/release/promise.js:638:18)
    at /Users/./.atom/packages/markdown-pdf/node_modules/bluebird/js/release/nodeback.js:42:21
    at tryToString (fs.js:426:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:413:12)
(anonymous) @ markdown-pdf.js [sm]:135
step @ /Users/./.atom/packages/markdown-pdf/lib/markdown-pdf.js:1
markdown-pdf.js [sm]:157 TypeError: mdpreview.mainModule.copyHTML is not a function
    at Object.htmlFromPreview (fallback.js [sm]:32)
    at Object.<anonymous> (fallback.js [sm]:27)
    at Generator.next (<anonymous>)
    at step (fallback.js [sm]:28)
    at fallback.js [sm]:28
    at Object.convert (fallback.js [sm]:28)
    at HTMLElement.<anonymous> (markdown-pdf.js [sm]:137)
    at Generator.throw (<anonymous>)
    at step (/Users/./.atom/packages/markdown-pdf/lib/markdown-pdf.js:1)
(anonymous) @ markdown-pdf.js [sm]:157
(anonymous) @ markdown-pdf.js [sm]:158
step @ /Users/./.atom/packages/markdown-pdf/lib/markdown-pdf.js:1
markdown-pdf.js [sm]:135 AssertionError: html-pdf: Failed to load PhantomJS module. You have to set the path to the PhantomJS binary using 'options.phantomPath'
    at new PDF (/Users/./.atom/packages/markdown-pdf/node_modules/mdpdf/node_modules/html-pdf/lib/pdf.js:38:3)
    at Object.createPdf [as create] (/Users/./.atom/packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/dependencies/node-html-pdf/index.js:10:14)
    at Promise (/Users/./.atom/packages/markdown-pdf/node_modules/mdpdf/index.js:177:7)
    at Promise._execute (/Users/./.atom/packages/markdown-pdf/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/Users/./.atom/packages/markdown-pdf/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/./.atom/packages/markdown-pdf/node_modules/bluebird/js/release/promise.js:79:10)
    at createPdf (/Users/./.atom/packages/markdown-pdf/node_modules/mdpdf/index.js:176:9)
    at readFile.then.then.then.then.md (/Users/./.atom/packages/markdown-pdf/node_modules/mdpdf/index.js:169:10)
    at tryCatcher (/Users/./.atom/packages/markdown-pdf/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/./.atom/packages/markdown-pdf/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/./.atom/packages/markdown-pdf/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/./.atom/packages/markdown-pdf/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/./.atom/packages/markdown-pdf/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/./.atom/packages/markdown-pdf/node_modules/bluebird/js/release/promise.js:638:18)
    at /Users/./.atom/packages/markdown-pdf/node_modules/bluebird/js/release/nodeback.js:42:21
    at tryToString (fs.js:426:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:413:12)
(anonymous) @ markdown-pdf.js [sm]:135
step @ /Users/./.atom/packages/markdown-pdf/lib/markdown-pdf.js:1
markdown-pdf.js [sm]:157 TypeError: mdpreview.mainModule.copyHTML is not a function
    at Object.htmlFromPreview (fallback.js [sm]:32)
    at Object.<anonymous> (fallback.js [sm]:27)
    at Generator.next (<anonymous>)
    at step (fallback.js [sm]:28)
    at fallback.js [sm]:28
    at Object.convert (fallback.js [sm]:28)
    at HTMLElement.<anonymous> (markdown-pdf.js [sm]:137)
    at Generator.throw (<anonymous>)
    at step (/Users/./.atom/packages/markdown-pdf/lib/markdown-pdf.js:1)
(anonymous) @ markdown-pdf.js [sm]:157
(anonymous) @ markdown-pdf.js [sm]:158
step @ /Users/./.atom/packages/markdown-pdf/lib/markdown-pdf.js:1

**Comment by dj325** [comment]
I've recently been hit with precisely the same problem. Running Atom 1.26.1 on Ubuntu 18:
`AssertionError: html-pdf: Failed to load PhantomJS module. You have to set the path to the PhantomJS binary using 'options.phantomPath'`

**Comment by travs** [comment]
Fixed with upgrade to pupeteer instead of phantomjs as primary rendering engine
