### ISSUE TITLE
Failed to activate the markdown-pdf package

### ISSUE THREAD

**Issue by Lounaver** [travs/markdown-pdf#232]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Unknown Windows version
**Thrown From**: [markdown-pdf](https://github.com/travs/markdown-pdf) package 2.3.3

### Stack Trace

Failed to activate the markdown-pdf package

```
At Cannot find module 'less'
Require stack:
- C:\Users\Lenovo\.atom\packages\markdown-pdf\lib\actions\convert.js
- C:\Users\Lenovo\.atom\packages\markdown-pdf\lib\markdown-pdf.js
- C:\Users\Lenovo\AppData\Local\atom\app-1.48.0\resources\app.asar\static\index.html

Error: Cannot find module 'less'
Require stack:
- C:\Users\Lenovo\.atom\packages\markdown-pdf\lib\actions\convert.js
- C:\Users\Lenovo\.atom\packages\markdown-pdf\lib\markdown-pdf.js
- C:\Users\Lenovo\AppData\Local\atom\app-1.48.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:683:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.48.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:155487)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:146819)
    at /packages/markdown-pdf/lib/actions/convert.js:4:20)
    at /packages/markdown-pdf/lib/actions/convert.js:114:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:147503)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:146819)
    at /packages/markdown-pdf/lib/markdown-pdf.js:4:30)
    at /packages/markdown-pdf/lib/markdown-pdf.js:29:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:147503)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:1:735013)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:3308385)
    at Package.activateNow (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:3296369)
    at ~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:1879
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:1201460)
    at Emitter.emit (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:1202901)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:349418)
```

### Commands

```
     -0:19.6.0 markdown-pdf:open-settings (atom-pane.pane.active)
     -0:14.6.0 markdown-pdf:convert (atom-pane.pane.active)
```

### Non-Core Packages

```
@less/root 1000.0.0 
markdown-pdf 2.3.3 
pdf-view 0.72.0 
```

**Comment by TamaMcGlinn** [comment]
I ran into this when attempting an offline install:

1. Install atom
2. Copy this repository into the packages directory, so that e.g. `C:\Users\[name]\.atom\packages\markdown-pdf\README.md` exists.
3. Open a markdown file in atom and try `packages > markdown to pdf > convert`

**Comment by aperezbios** [comment]
Same. I guess it's never getting fixed by the author?
