### ISSUE TITLE
Uncaught ReferenceError: outPath is not defined

### ISSUE THREAD

**Issue by davidB** [travs/markdown-pdf#26]
[Enter steps to reproduce below:]

0. I didn't touch settings off the package
1. Open a .md file In left pane , markdown preview in right pane
2. focus on left pane (.md)
3. Call convert (Ctrl+Shift+C or via command palette)

**Atom Version**: 0.165.0
**System**: linux 3.17.6-1-ARCH
**Thrown From**: [markdown-pdf](https://github.com/travs/markdown-pdf) package, v1.2.11

### Stack Trace

Uncaught ReferenceError: outPath is not defined

```
At /home/dwayne/.atom/packages/markdown-pdf/lib/markdown-pdf.js:154

ReferenceError: outPath is not defined
  at processSrc (/home/dwayne/.atom/packages/markdown-pdf/lib/markdown-pdf.js:154:37)
  at convertImgSrcToURI (/home/dwayne/.atom/packages/markdown-pdf/lib/markdown-pdf.js:140:19)
  at /home/dwayne/.atom/packages/markdown-pdf/lib/markdown-pdf.js:64:14
  at htmlFromMd (/home/dwayne/.atom/packages/markdown-pdf/lib/markdown-pdf.js:88:5)
  at atom-workspace.module.exports.convert (/home/dwayne/.atom/packages/markdown-pdf/lib/markdown-pdf.js:63:5)
  at atom-workspace.handler (/usr/share/atom/resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:167:20)

```

### Commands

```
     -2:17.0 command-palette:toggle (input.hidden-input)
     -2:12.3 core:confirm (input.hidden-input)
     -2:12.3 markdown-pdf:convert (input.hidden-input)
     -1:23.4 settings-view:install-packages (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:04.9 command-palette:toggle (input.hidden-input)
  2x -0:00.0 markdown-pdf:convert (input.hidden-input)
```

### Config

```
{
  "core": {
    "disabledPackages": [
      "linter-coffeelint"
    ]
  },
  "markdown-pdf": {}
}
```

### Installed Packages

```coffee
# User
external-open, v0.3.0
git-log, v0.2.0
language-glsl, v0.2.2
language-gradle, v0.0.3
language-groovy, v0.3.0
language-protobuf, v0.2.1
linter, v0.10.0
linter-flake8, v1.2.0
linter-pylint, v0.2.0
markdown-pdf, v1.2.11
recent-projects, v0.2.6

# Dev
No dev packages
```

/cc @atom/core

**Comment by travs** [comment]
Going to have a deeper look later, but was the markdown document you wanted to convert saved already?

**Comment by davidB** [comment]
Yes it was an existing file. I restarted my atom, Since I no longer have the issue. I'd got the issue after first install without restart.

Thanks for the package.
