### ISSUE TITLE
Uncaught TypeError: object is not a function

### ISSUE THREAD

**Issue by martymcflywa** [travs/markdown-pdf#84]
[Enter steps to reproduce below:]

1. Open a markdown file
2. Press CTRL+SHIFT+E to export

Right clicking in markdown preview also does nothing.

**Atom Version**: 1.0.9
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [markdown-pdf](https://github.com/travs/markdown-pdf) package, v1.3.9

### Stack Trace

Uncaught TypeError: object is not a function

```
At C:\Users\marty\.atom\packages\markdown-pdf\node_modules\html-pdf\lib\index.js:58

TypeError: object is not a function
  at C:\Users\marty\.atom\packages\markdown-pdf\node_modules\html-pdf\lib\index.js:58:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -1:01.0 markdown-themeable-pdf:export (atom-text-editor.editor.is-focused)
     -0:40.9.0 markdown-preview:toggle (atom-text-editor.editor.is-focused)
     -0:07.2.0 markdown-themeable-pdf:export (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "autoHideMenuBar": true,
    "projectHome": "C:\\Users\\marty\\Dropbox\\Documents\\ecu"
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.18.0
language-asp, v1.0.0
language-aspx, v0.4.0
language-latex, v0.6.1
markdown-scroll-sync, v0.4.0
markdown-themeable-pdf, v0.7.2
save-session, v0.15.7
sync-settings, v0.6.0
tabs-to-spaces, v0.11.1

# Dev
No dev packages
```

**Comment by travs** [comment]
Should be fixed by #59
