### ISSUE TITLE
Uncaught Error: Cannot find module 'phantomjs'

### ISSUE THREAD

**Issue by seandon** [travs/markdown-pdf#87]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.15
**System**: Unknown Windows Version
**Thrown From**: [markdown-pdf](https://github.com/travs/markdown-pdf) package, v1.3.9

### Stack Trace

Uncaught Error: Cannot find module 'phantomjs'

```
At module.js:336

Error: Cannot find module 'phantomjs'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (C:\Users\亮亮唐\AppData\Local\atom\app-1.0.15\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\亮亮唐\.atom\packages\markdown-pdf\node_modules\html-pdf\lib\index.js:9:13)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (C:\Users\亮亮唐\AppData\Local\atom\app-1.0.15\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\亮亮唐\.atom\packages\markdown-pdf\node_modules\html-pdf\index.js:1:69)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (C:\Users\亮亮唐\AppData\Local\atom\app-1.0.15\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\亮亮唐\.atom\packages\markdown-pdf\lib\markdown-pdf.js:2:11)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (C:\Users\亮亮唐\AppData\Local\atom\app-1.0.15\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\亮亮唐\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:761:34)
  at Package.module.exports.Package.activateConfig (C:\Users\亮亮唐\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:263:14)
  at PackageDetailView.module.exports.PackageDetailView.activateConfig (C:\Users\亮亮唐\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:212:26)
  at PackageDetailView.module.exports.PackageDetailView.completeInitialzation (C:\Users\亮亮唐\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:156:12)
  at PackageDetailView.module.exports.PackageDetailView.loadPackage (C:\Users\亮亮唐\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:168:21)
  at C:\Users\亮亮唐\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:298:17
  at Emitter.module.exports.Emitter.emit (C:\Users\亮亮唐\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (C:\Users\亮亮唐\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\package-manager.js:588:27)
  at C:\Users\亮亮唐\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\package-manager.js:379:26
  at exit (C:\Users\亮亮唐\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\package-manager.js:60:16)
  at triggerExitCallback (C:\Users\亮亮唐\AppData\Local\atom\app-1.0.15\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\亮亮唐\AppData\Local\atom\app-1.0.15\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```

### Commands

```
     -2:20.2.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:14.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:14.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -2:11.1.0 welcome:show (atom-pane.pane.active)
     -1:48.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by SamCB** [comment]
Happened to me as well, using 15-inch, Early 2011 Macbook Pro Running OSx Yosemite Version 10.10.5. Atom 1.0.8.

I tried installing this but the install was taking too long, seemed as if it hanged, I closed atom, tried again.

As soon as the install finished, bug message popped up. Dismissed. Was able to find markdown-pdf in the command pallet but clicking on it with a `.md` file open did nothing. After that, it was no longer in the command pallet.

----

I managed to fix it by uninstalling markdown-pdf then re-installing.

**Comment by travs** [comment]
as @SamCB mentioned, uninstalling/reinstalling seems to work for this. Seems to be related to PhantomJS unavailability?

**Comment by liuwons** [comment]
This happened to me, too. But cannot be fixed by uninstall/reinstall.
**Windows7** 64bit. **Atom** 1.5.4
Here is the error message:
```
Uncaught AssertionError: html-pdf: Failed to load PhantomJS module. 
You have to set the path to the PhantomJS binary using 'options.phantomPath'
```
Seems like `phantomjs-prebuilt` can't be found.

**Comment by vmourac** [comment]
For me simply uninstalling/reinstalling did not work. 
What I did was navigating into the extension directory, deleting the "node_modules" folder and running "npm install" from scratch.
