### ISSUE TITLE
Uncaught Error: write EPIPE

### ISSUE THREAD

**Issue by MishChen** [travs/markdown-pdf#89]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Ubuntu 14.04.3
**Thrown From**: [markdown-pdf](https://github.com/travs/markdown-pdf) package, v1.3.9

### Stack Trace

Uncaught Error: write EPIPE

```
At events.js:141

Error: write EPIPE
  at Object.exports._errnoException (util.js:814:11)
  at exports._exceptionWithHostPort (util.js:837:20)
  at WriteWrap.afterWrite (net.js:757:14)
  at EventEmitter.ipc.sendSync (/usr/share/atom/resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at Object.RemoteMemberFunction [as readText] (/usr/share/atom/resources/atom.asar/renderer/api/lib/remote.js:140:29)
  at Clipboard.module.exports.Clipboard.read (/usr/share/atom/resources/app.asar/src/clipboard.js:26:24)
  at htmlFromPreview (/home/mish/.atom/packages/markdown-pdf/lib/markdown-pdf.js:85:18)
  at atom-workspace.module.exports.convert (/home/mish/.atom/packages/markdown-pdf/lib/markdown-pdf.js:57:7)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:245:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:145:19)
  at EventEmitter.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:169:7)

```

### Commands

```
     -6:20.3.0 command-palette:toggle (div.markdown-preview.native-key-bindings)
 20x -6:06.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -3:20.5.0 core:move-up (atom-text-editor.editor.is-focused)
  3x -3:18.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:16.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -3:15.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -3:14.8.0 core:move-down (atom-text-editor.editor.is-focused)
     -3:14.3.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -3:13.4.0 core:move-up (atom-text-editor.editor.is-focused)
     -3:11.6.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -3:09.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.8.0 markdown-pdf:convert (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "markdown-pdf": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.14
colorful-json, v1.0.0
json-schema, v0.1.15
markdown-pdf, v1.3.9
markdown-preview-plus, v2.2.0
pretty-json, v0.4.1

# Dev
No dev packages
```

**Comment by travs** [comment]
Ok, since we use a newer version of `html-pdf`, this is probably fixed. Closing for now.
