### ISSUE TITLE
Install silently fails

### ISSUE THREAD

**Issue by DavidAwad** [travs/markdown-pdf#90]
Looking in the developer console, it looks like PhantomJS is required for this package to work.

I'm on El Capitan and brew complains when trying to install phantomjs that way. 

However after installing phantomjs globally with `npm install -g phantomjs`, installation still failed. 

Sent a small PR to list this as a requirement : )

```Javascript
Installing package markdown-pdf failed Error: Installing “markdown-pdf@undefined” failed.
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:384:21
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:60:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
 
> phantomjs@1.9.18 install /private/var/folders/m1/7nw07p6x6m577j25c96fdwh00000gn/T/apm-install-dir-115921-70919-1rupgxd/node_modules/markdown-pdf/node_modules/html-pdf/node_modules/phantomjs
> node install.js


npm ERR! Darwin 15.0.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/david/.atom/.apm/.apmrc" "--userconfig" "/Users/david/.atom/.apmrc" "install" "/private/var/folders/m1/7nw07p6x6m577j25c96fdwh00000gn/T/d-115921-70919-xsucug/package.tgz" "--target=0.30.7" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! phantomjs@1.9.18 install: `node install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.18 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/m1/7nw07p6x6m577j25c96fdwh00000gn/T/apm-install-dir-115921-70919-1rupgxd/npm-debug.log
```

**Comment by travs** [comment]
There seems to be a problem with phantomjs availability sometimes, and uninstalling/reinstalling seems to fix it.

Will add this to the readme if the issue persists, since there have been major updates recently.

**Comment by miccferr** [comment]
+1 
just had similar error when upgrading the package:
```

> phantomjs@1.9.20 install /private/var/folders/hc/40yjf1gd2c5_mxc640c329yh0000gn/T/apm-install-dir-116312-4847-99nlee/node_modules/markdown-pdf/node_modules/html-pdf/node_modules/phantomjs
> node install.js


npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm ERR! Darwin 15.0.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/mferretti/.atom/.apm/.apmrc" "--userconfig" "/Users/mferretti/.atom/.apmrc" "install" "/private/var/folders/hc/40yjf1gd2c5_mxc640c329yh0000gn/T/d-116312-4847-1e7ko6e/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! phantomjs@1.9.20 install: `node install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.20 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/hc/40yjf1gd2c5_mxc640c329yh0000gn/T/apm-install-dir-116312-4847-99nlee/npm-debug.log

```
