### ISSUE TITLE
Uncaught TypeError: callback is not a function

### ISSUE THREAD

**Issue by shavyg2** [travs/markdown-pdf#94]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [markdown-pdf](https://github.com/travs/markdown-pdf) package, v1.3.9

### Stack Trace

Uncaught TypeError: callback is not a function

```
At C:\Users\shavauhng\.atom\packages\markdown-pdf\node_modules\html-pdf\lib\index.js:58

TypeError: callback is not a function
  at C:\Users\shavauhng\.atom\packages\markdown-pdf\node_modules\html-pdf\lib\index.js:58:18
  at FSReqWrap.oncomplete (fs.js:82:15)

```

### Commands

```
     -1:26.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:18.9.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -1:15.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:00.4.0 core:move-left (atom-text-editor.editor.is-focused)
  3x -0:59.5.0 core:backspace (atom-text-editor.editor.is-focused)
  4x -0:51.4.0 core:move-left (atom-text-editor.editor.is-focused)
  5x -0:49.4.0 core:select-right (atom-text-editor.editor.is-focused)
  8x -0:47.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:33.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:29.1.0 core:move-down (atom-text-editor.editor.is-focused)
  8x -0:28.6.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:27.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:10.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:06.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:03.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.7.0 markdown-themeable-pdf:export (atom-text-editor.editor)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v7.7.0
autocomplete-modules, v1.3.1
color-picker, v2.0.13
jsformat, v0.9.0
linter, v1.10.0
markdown-pdf, v1.3.9
markdown-scroll-sync, v0.4.2
markdown-themeable-pdf, v0.10.1
node-resolver, v1.0.1
pigments, v0.18.1
sass-compiler, v0.4.0

# Dev
No dev packages
```

**Comment by travs** [comment]
Should be fixed by #59
